# Build settings
permalink   : /blog/:year/:title/
markdown    : kramdown
highlighter : pygments
gems: [jekyll-paginate]

paginate: 3
paginate_path: "/blog/page/:num/"
comments: true


destination: _site
sass:
  sass_dir: _scss
  style: compressed # expanded

# SEO settings
title: Mohamed Alouane
description: "Mohamed Alouane, a Web and Mobile developer"
keywords: "alouanemed,alouane med, alouane mohamed"
url: http://malouane.com
baseurl: ""
# baseurl: ""

# google_analytics: UA-
repo: http://github.com/alouanemed
disqus_shortname: "alouanemed"
disqus_site_shortname: "alouanemed"

# Author settings
author:
  name      : Mohamed Alouane
  job       : Rails developer and Full stack Android developer
  bio       : "A deeply motivated and passionated Robot with feelings, a lot of them. Ruby On Rails and Java developer, Android Ninja, Active OSS contributor and Git power user.Always looking for the best project and good coffee."
  thumb     : /images/author.jpg
  email     : 3louane@gmail.com
  url       : http://malouane.com
  github    : http://github.com/alouanemed
  twitter   : http://twitter.com/alouanemed
  facebook  : http://facebook.com/alouanemed
  linkedin  : http://linkedin.com/in/alouanemed

# navbar pages
navbar:
  - slug: about
    title: About
  - slug: resume
    title: Resume
  # - slug: skills
  #   title: Skills
  - slug: blog
    title: Blog

gems:
  - jekyll-seo-tag
  - jekyll-paginate

twitter:
  - username: alouanemed

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
